- name: Instalaci贸n de los paquetes necesarios de la aplicaci贸n de Hosting
  shell: apt install geany python-bottle python-setuptools git python-beaker -y

- copy:
    src: ldap3-master.zip
    dest: /home/usuario/Plantillas/ldap3-master.zip

- copy:
    src: PyGithub-master.zip                     
    dest: /home/usuario/Plantillas/PyGithub-master.zip

- name: Descomprimiendo LDAP3
  shell: cd /home/usuario/Plantillas/ && sudo unzip ldap3-master.zip

- name: Descomprimiendo PyGithub
  shell: cd /home/usuario/Plantillas/ && sudo unzip PyGithub-master.zip
 
- name: Instalaci贸n de LDAP3
  shell: cd /home/usuario/Plantillas/ldap3-master && sudo python setup.py install

- name: Instalando PyGithub
  shell: cd /home/usuario/Plantillas/PyGithub-master && sudo python setup.py install

- copy:
    src: aplicacion
    dest: /home/usuario/
    directory_mode: yes

- name: Copiando fichero aplicacion.py
  template: >
    src=aplicacion.py
    dest=/home/usuario/aplicacion/aplicacion.py

- name: Cambiando permisos a static
  shell: sudo chgrp -R www-data /home/usuario/aplicacion/static

- name: Cambiando permisos a views
  shell: sudo chgrp -R www-data /home/usuario/aplicacion/views
  shell: sudo chmod -R 755 /home/usuario/aplicacion

- name: Haciendo la aplicaci贸n ejecutable por el usuario
  shell: sudo chown -R usuario:usuario /home/usuario/aplicacion

- name: Creando directorio Users
  file: path=/home/users state=directory
