- name: instalación de apache, php5 y curl
  apt: name={{item}} state=installed
  with_items:
       - apache2
       - php5
       - php5-curl

- copy:
    src: spotype.conf
    dest: /etc/apache2/sites-available/spotype.conf
    owner: root
    group: root
    mode: 644

- copy:
    src: phpmyadmin.conf
    dest: /etc/apache2/sites-available/phpmyadmin.conf
    owner: root
    group: root
    mode: 644

- copy:
    src: apache2.conf
    dest: /etc/apache2/apache2.conf
    owner: root
    group: root
    mode: 0644

- name: Deshabilitando el sitio por defecto
  shell: sudo a2dissite 000-default.conf

- name: Habilitando el sitio de Spotype.com
  shell: sudo a2ensite spotype.conf

- name: Habilitando el sitio de phpmyadmin
  shell: sudo a2ensite phpmyadmin.conf

- name: Habilitando modulos de apache2
  action: command a2enmod rewrite
  notify: reinicio del servicio de Apache
