- name: Variables de phpmyadmin
  include_vars: "main.yml"

- name: Fichero de configuraci칩n de phpmyadmin
  set_fact:
    phpmyadmin_config_file: "{{ __phpmyadmin_config_file }}"
  when: phpmyadmin_config_file is not defined

- include: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: A침adimos usuario y contrase침as root para la conexi칩n con mysql
  lineinfile: >
    dest={{ phpmyadmin_config_file }}
    state=present
    regexp="^.+\['{{ item.key }}'\].+$"
    line="$cfg['Servers'][$i]['{{ item.key }}'] = '{{ item.value }}';"
    insertbefore="^\?>"
  with_items:
  - { key: host, value: "{{ phpmyadmin_mysql_host }}" }
  - { key: port, value: "{{ phpmyadmin_mysql_port }}" }
  - { key: socket, value: "{{ phpmyadmin_mysql_socket }}" }
  - { key: connect_type, value: "{{ phpmyadmin_mysql_connect_type }}" }
  - { key: user, value: "{{ phpmyadmin_mysql_user }}" }
  - { key: password, value: "{{ phpmyadmin_mysql_password }}"}
