- name: Asegurarse de que phpmyadmin está instalado
  apt: name=phpmyadmin state=installed
  notify: reinicio del servicio de Apache

- name: Asegurarse de la configuración de phpmyadmin en apache2
  lineinfile:
    dest: /etc/apache2/apache2.conf
    state: present
    regexp: "^Include.+phpmyadmin.+$"
    line: "Include /etc/phpmyadmin/apache.conf"
    insertafter: "EOF"
  notify: reinicio del servicio de Apache
